# Generated by Django 5.2.7 on 2025-12-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='audio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='reel',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
