# Generated by Django 5.2.7 on 2025-12-04 10:46

import django.db.models.deletion
import mediafiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('original_file', models.FileField(max_length=500, upload_to=mediafiles.models.user_media_path)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('small', models.ImageField(blank=True, null=True, upload_to='small/')),
                ('medium', models.ImageField(blank=True, null=True, upload_to='medium/')),
                ('large', models.ImageField(blank=True, null=True, upload_to='large/')),
                ('webp', models.ImageField(blank=True, null=True, upload_to='webp/')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('processed_audio', models.FileField(blank=True, null=True, upload_to='processed_audio/')),
                ('bitrate', models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'file_type', '-created_at'], name='mediafiles__user_id_78a01e_idx'), models.Index(fields=['status', '-created_at'], name='mediafiles__status_2d2d2f_idx')],
            },
        ),
    ]
