# Generated by Django 5.2.11 on 2026-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_attributedefinition_attributeoption_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="rejected_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("expired", "Expired"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
