# Generated by Django 5.2.11 on 2026-02-25 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_listingpromotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("follow_request", "Follow Request"),
                    ("follow_accept", "Follow Accept"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("mention", "Mention"),
                    ("saved_search", "Saved Search Match"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255, null=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("instant", "Instant"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
