# Generated by Django 5.2.11 on 2026-02-25 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="delivery_radius",
            field=models.PositiveIntegerField(
                blank=True, help_text="Delivery radius in km", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="local_pickup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="shipping_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="shipping_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_option",
                    models.CharField(
                        choices=[("shipping", "Shipping"), ("pickup", "Local Pickup")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_bought",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.listing",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_sold",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
