# Generated by Django 5.2.11 on 2026-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_profile_is_online_profile_last_seen_messagereaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_for_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_for_sender",
            field=models.BooleanField(default=False),
        ),
    ]
