# Generated by Django 5.2.11 on 2026-02-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_conversation_admins_conversation_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="priority",
            field=models.CharField(
                choices=[("normal", "Normal"), ("high", "High")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payout_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
