# Generated by Django 5.2.11 on 2026-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_subscriptionplan_profile_referral_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("new_posts", models.PositiveIntegerField(default=0)),
                ("new_listings", models.PositiveIntegerField(default=0)),
                ("new_orders", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("rollout_percentage", models.PositiveSmallIntegerField(default=100)),
            ],
        ),
    ]
