# Generated by Django 5.2.11 on 2026-02-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_listing_search_vector_post_search_vector_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="listings/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
