# Generated by Django 5.2.11 on 2026-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_listingmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("verified", "Verified Users"),
                            ("sellers", "Sellers"),
                            ("premium", "Premium Subscribers"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="payout",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="proof_of_payment",
            field=models.ImageField(blank=True, null=True, upload_to="payout_proofs/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="dashboard_layout",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="alerts_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("investigating", "Investigating"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("escalated", "Escalated"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
