# Generated by Django 4.2.27 on 2025-12-05 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live/thumbnails/')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('ended', 'Ended')], default='waiting', max_length=20)),
                ('viewer_count', models.IntegerField(default=0)),
                ('peak_viewer_count', models.IntegerField(default=0)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('heart', '❤️'), ('fire', '🔥'), ('clap', '👏'), ('laugh', '😂'), ('wow', '😮')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='live.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='live.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['stream', 'is_active'], name='live_livevi_stream__d04aeb_idx')],
                'unique_together': {('stream', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['status', '-created_at'], name='live_livest_status_a97c75_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['streamer', '-created_at'], name='live_livest_streame_3332be_idx'),
        ),
        migrations.AddIndex(
            model_name='livereaction',
            index=models.Index(fields=['stream', '-created_at'], name='live_livere_stream__75357f_idx'),
        ),
        migrations.AddIndex(
            model_name='livecomment',
            index=models.Index(fields=['stream', '-created_at'], name='live_liveco_stream__4d746e_idx'),
        ),
    ]
