# Generated by Django 5.2.7 on 2025-12-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_push', models.BooleanField(default=True)),
                ('like_email', models.BooleanField(default=False)),
                ('like_in_app', models.BooleanField(default=True)),
                ('comment_push', models.BooleanField(default=True)),
                ('comment_email', models.BooleanField(default=True)),
                ('comment_in_app', models.BooleanField(default=True)),
                ('follow_push', models.BooleanField(default=True)),
                ('follow_email', models.BooleanField(default=False)),
                ('follow_in_app', models.BooleanField(default=True)),
                ('message_push', models.BooleanField(default=True)),
                ('message_email', models.BooleanField(default=False)),
                ('message_in_app', models.BooleanField(default=True)),
                ('mention_push', models.BooleanField(default=True)),
                ('mention_email', models.BooleanField(default=True)),
                ('mention_in_app', models.BooleanField(default=True)),
                ('fcm_tokens', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', '-created_at'], name='notificatio_recipie_7b2be0_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
